on:
  pull_request:  

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        pure-python: [true, false]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install eventfd
      run: |
        python setup.py install
    - name: Test
      env:
        EVENTFD_PUREPYTHON: ${{ matrix.pure-python }}
      run: |
        python test/test_eventfd.py