on:
  pull_request:  
  push:

name: CI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        pure-python: [true, false]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build wheel
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        python setup.py bdist_wheel
    - name: Upload wheel
      if: ${{ matrix.os != 'windows-latest' }}
      uses: actions/upload-artifact@v2
      with:
        name: wheel-${{ matrix.os }}
        path: dist
    - name: Install eventfd
      run: |
        python setup.py install
    - name: Test
      env:
        EVENTFD_PUREPYTHON: ${{ matrix.pure-python }}
      run: |
        python test/test_eventfd.py
